/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    CultivationStatusBar: typeof import('./src/components/cultivation/CultivationStatusBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    MapNode: typeof import('./src/components/cultivation/MapNode.vue')['default']
    NoteTree: typeof import('./src/components/notes/NoteTree.vue')['default']
    NoteViewer: typeof import('./src/components/notes/NoteViewer.vue')['default']
    NpcTimeline: typeof import('./src/components/cultivation/NpcTimeline.vue')['default']
    RealmProgress: typeof import('./src/components/cultivation/RealmProgress.vue')['default']
    ResourceSummary: typeof import('./src/components/cultivation/ResourceSummary.vue')['default']
    RewardToast: typeof import('./src/components/cultivation/RewardToast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TechniqueSlotGrid: typeof import('./src/components/cultivation/TechniqueSlotGrid.vue')['default']
    TreeItem: typeof import('./src/components/TreeItem.vue')['default']
    TribulationProbability: typeof import('./src/components/cultivation/TribulationProbability.vue')['default']
    UpdatePrompt: typeof import('./src/components/layout/UpdatePrompt.vue')['default']
  }
}
