/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    CollaborativeMarkdownEditor: typeof import('./src/components/notes/CollaborativeMarkdownEditor.vue')['default']
    CultivationRetreatModal: typeof import('./src/components/retreat/CultivationRetreatModal.vue')['default']
    CultivationStatusBar: typeof import('./src/components/cultivation/CultivationStatusBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EncounterCatalogDrawer: typeof import('./src/components/retreat/EncounterCatalogDrawer.vue')['default']
    EncounterScrollDialog: typeof import('./src/components/retreat/EncounterScrollDialog.vue')['default']
    HabitHistoryDialog: typeof import('./src/components/HabitHistoryDialog.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    MapNode: typeof import('./src/components/cultivation/MapNode.vue')['default']
    NotebookMembersDialog: typeof import('./src/components/notes/NotebookMembersDialog.vue')['default']
    NoteTree: typeof import('./src/components/notes/NoteTree.vue')['default']
    NoteViewer: typeof import('./src/components/notes/NoteViewer.vue')['default']
    NpcTimeline: typeof import('./src/components/cultivation/NpcTimeline.vue')['default']
    RealmProgress: typeof import('./src/components/cultivation/RealmProgress.vue')['default']
    ResourceSummary: typeof import('./src/components/cultivation/ResourceSummary.vue')['default']
    RetreatCountdownRing: typeof import('./src/components/retreat/RetreatCountdownRing.vue')['default']
    RewardToast: typeof import('./src/components/cultivation/RewardToast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TechniqueSlotGrid: typeof import('./src/components/cultivation/TechniqueSlotGrid.vue')['default']
    TodayActionCenter: typeof import('./src/components/home/TodayActionCenter.vue')['default']
    TodayWorkbench: typeof import('./src/components/home/TodayWorkbench.vue')['default']
    TreeItem: typeof import('./src/components/TreeItem.vue')['default']
    TribulationProbability: typeof import('./src/components/cultivation/TribulationProbability.vue')['default']
    UpdatePrompt: typeof import('./src/components/layout/UpdatePrompt.vue')['default']
    WorkbenchTaskRow: typeof import('./src/components/home/WorkbenchTaskRow.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
