// LifeQuest Shop Icons Registry (320 Icons)
import {
  Activity,
  Airplay,
  AlarmClock,
  Anchor,
  Apple,
  Armchair,
  Atom,
  Award,
  BadgeCheck,
  BadgeDollarSign,
  BadgePercent,
  Banana,
  Banknote,
  BarChart3,
  Barcode,
  Bath,
  BatteryCharging,
  BatteryFull,
  Bean,
  Bed,
  BedDouble,
  Beef,
  Beer,
  BeerOff,
  Bell,
  BicepsFlexed,
  Bike,
  Binary,
  Bird,
  Blocks,
  Bluetooth,
  Book,
  BookCopy,
  BookHeart,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Bookmark,
  BoomBox,
  Bot,
  Brain,
  Briefcase,
  Brush,
  Bus,
  Cake,
  CakeSlice,
  Calculator,
  Camera,
  Candy,
  CandyCane,
  Car,
  CarTaxiFront,
  Caravan,
  Carrot,
  CassetteTape,
  Cast,
  Castle,
  Cat,
  CheckCheck,
  ChefHat,
  Cherry,
  Church,
  Citrus,
  Clapperboard,
  Clock,
  CloudRain,
  CloudSun,
  Clover,
  Code,
  Coffee,
  Coins,
  Compass,
  Component,
  Contrast,
  Cookie,
  CookingPot,
  Cpu,
  CreditCard,
  Croissant,
  Crosshair,
  Crown,
  CupSoda,
  Database,
  Dessert,
  Diamond,
  Dice1,
  Dice2,
  Dice5,
  Dice6,
  Disc,
  Dna,
  Dog,
  Donut,
  DoorClosed,
  DoorOpen,
  Drama,
  Droplet,
  Drumstick,
  Dumbbell,
  Earth,
  Egg,
  EggFried,
  Eraser,
  Feather,
  Figma,
  FileCode,
  FileCode2,
  FileSpreadsheet,
  FileText,
  Film,
  Fingerprint,
  Fish,
  FishSymbol,
  Flag,
  Flame,
  FlameKindling,
  FlaskConical,
  FlaskRound,
  Flower,
  Flower2,
  FolderKanban,
  Footprints,
  Fuel,
  Gamepad,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitCommitHorizontal,
  GlassWater,
  Glasses,
  Globe,
  Goal,
  GraduationCap,
  Grape,
  Ham,
  HandCoins,
  HandHeart,
  HandMetal,
  HardDrive,
  Headphones,
  Headset,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  Helicopter,
  Highlighter,
  Home,
  Hop,
  Hotel,
  Hourglass,
  House,
  IceCream2,
  IceCreamBowl,
  Inbox,
  Joystick,
  Kanban,
  Key,
  KeyRound,
  Keyboard,
  Lamp,
  LampCeiling,
  LampDesk,
  Languages,
  Laptop,
  Laugh,
  Layers,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  ListTodo,
  Lollipop,
  Luggage,
  Map,
  MapPin,
  MapPinCheck,
  Martini,
  Medal,
  Mic,
  Mic2,
  Microwave,
  Milestone,
  Milk,
  Monitor,
  MonitorSpeaker,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  Mouse,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Network,
  Newspaper,
  Nut,
  Package,
  PackageCheck,
  PackageOpen,
  Palette,
  Palmtree,
  PartyPopper,
  Pen,
  PenLine,
  PenTool,
  Pencil,
  PencilRuler,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Podcast,
  Popcorn,
  Presentation,
  Projector,
  Puzzle,
  QrCode,
  Rabbit,
  Radio,
  RadioReceiver,
  Rainbow,
  Receipt,
  ReceiptText,
  Refrigerator,
  Ribbon,
  Rocket,
  Sailboat,
  Salad,
  Sandwich,
  Scale,
  Scan,
  School,
  Scissors,
  Send,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  Ship,
  ShipWheel,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Smartphone,
  Smile,
  SmilePlus,
  Snowflake,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  Sprout,
  Squirrel,
  Stamp,
  Star,
  Store,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  Sunrise,
  Sunset,
  Sword,
  Swords,
  Tablet,
  Tag,
  Tags,
  Target,
  Telescope,
  Tent,
  TentTree,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TicketCheck,
  TicketPercent,
  Timer,
  Tornado,
  Train,
  TrainFront,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Tv2,
  Umbrella,
  Utensils,
  UtensilsCrossed,
  Vault,
  Video,
  Wallet,
  WalletCards,
  Wand2,
  WashingMachine,
  Watch,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Wine,
  WineOff,
  Workflow,
  Zap
} from 'lucide-vue-next'

export const iconCategories = [
  { id: 'all', name: '全部' },
  { id: 'food', name: '☕ 美食饮品' },
  { id: 'digital', name: '🎮 数码影音' },
  { id: 'leisure', name: '🏃 运动出行' },
  { id: 'reward', name: '🎁 礼品时尚' },
  { id: 'home', name: '🏡 居家休闲' },
  { id: 'study', name: '💻 学习成长' }
]

export const iconOptions = [
  { value: 'Coffee', label: '现磨咖啡', category: 'food', theme: 'amber', component: Coffee, keywords: '咖啡 拿铁 美式 星巴克 下午茶 提神' },
  { value: 'CupSoda', label: '爆汁冷饮', category: 'food', theme: 'amber', component: CupSoda, keywords: '奶茶 汽水 可乐 饮料 喜茶 霸气冷饮' },
  { value: 'Pizza', label: '意式披萨', category: 'food', theme: 'amber', component: Pizza, keywords: '披萨 必胜客 快餐 芝士 聚会 美食' },
  { value: 'Cake', label: '双层蛋糕', category: 'food', theme: 'amber', component: Cake, keywords: '蛋糕 生日 甜品 奶油 庆祝 派对' },
  { value: 'CakeSlice', label: '三角切块', category: 'food', theme: 'amber', component: CakeSlice, keywords: '小蛋糕 提拉米苏 芝士 甜点 下午茶' },
  { value: 'IceCream2', label: '脆筒雪糕', category: 'food', theme: 'amber', component: IceCream2, keywords: '甜筒 冰淇淋 雪糕 麦当劳 甜品' },
  { value: 'IceCreamBowl', label: '圣代雪球', category: 'food', theme: 'amber', component: IceCreamBowl, keywords: '圣代 冰淇淋球 芭菲 甜点 冷饮' },
  { value: 'Sandwich', label: '三明治简餐', category: 'food', theme: 'amber', component: Sandwich, keywords: '三明治 赛百味 汉堡 轻食 早餐' },
  { value: 'Croissant', label: '法式可颂', category: 'food', theme: 'amber', component: Croissant, keywords: '可颂 牛角面包 烘焙 早餐 咖啡伴侣' },
  { value: 'Drumstick', label: '香脆炸鸡', category: 'food', theme: 'amber', component: Drumstick, keywords: '炸鸡 烤鸡腿 麦辣 肯德基 烤肉' },
  { value: 'Beef', label: '厚切牛排', category: 'food', theme: 'amber', component: Beef, keywords: '牛排 牛肉 西餐 战斧 铁板 烤肉' },
  { value: 'Fish', label: '深海鲜鱼', category: 'food', theme: 'cyan', component: Fish, keywords: '海鲜 刺身 烤鱼 鱼肉 寿司 三文鱼' },
  { value: 'FishSymbol', label: '鲜活鱼生', category: 'food', theme: 'cyan', component: FishSymbol, keywords: '鲜鱼 锦鲤 生鲜 日料 刺身 鱼' },
  { value: 'Utensils', label: '西餐刀叉', category: 'food', theme: 'emerald', component: Utensils, keywords: '西餐 正餐 刀叉 餐厅 约会 美味' },
  { value: 'UtensilsCrossed', label: '欢聚盛宴', category: 'food', theme: 'amber', component: UtensilsCrossed, keywords: '聚餐 盛宴 大餐 火锅 宴席 聚会' },
  { value: 'Soup', label: '暖胃热汤', category: 'food', theme: 'amber', component: Soup, keywords: '靓汤 火锅 炖汤 热汤 暖胃 养生' },
  { value: 'Donut', label: '甜甜圈', category: 'food', theme: 'amber', component: Donut, keywords: '甜甜圈 糖霜 甜点 零食 多拿滋' },
  { value: 'Cookie', label: '曲奇脆饼', category: 'food', theme: 'amber', component: Cookie, keywords: '曲奇 饼干 烘焙 零食 休闲小食' },
  { value: 'Candy', label: '彩色水果糖', category: 'food', theme: 'purple', component: Candy, keywords: '糖果 软糖 水果糖 零食 甜蜜' },
  { value: 'CandyCane', label: '节日拐杖糖', category: 'food', theme: 'purple', component: CandyCane, keywords: '拐杖糖 圣诞 糖果 节日 欢庆' },
  { value: 'Lollipop', label: '波板棒棒糖', category: 'food', theme: 'amber', component: Lollipop, keywords: '棒棒糖 甜蜜 糖果 零食 快乐' },
  { value: 'Popcorn', label: '影院爆米花', category: 'food', theme: 'amber', component: Popcorn, keywords: '爆米花 焦糖 电影院 零食 追剧' },
  { value: 'Beer', label: '精酿麦啤', category: 'food', theme: 'amber', component: Beer, keywords: '啤酒 精酿 生啤 麦芽 聚会畅饮' },
  { value: 'BeerOff', label: '健康戒酒', category: 'food', theme: 'emerald', component: BeerOff, keywords: '戒酒 清醒 健康自律 节制' },
  { value: 'Wine', label: '陈年红酒', category: 'food', theme: 'purple', component: Wine, keywords: '红酒 葡萄酒 高脚杯 浪漫 晚宴 微醺' },
  { value: 'WineOff', label: '健康少饮', category: 'food', theme: 'emerald', component: WineOff, keywords: '少酒 节制 健康自律 清爽生活' },
  { value: 'GlassWater', label: '清冽纯水', category: 'food', theme: 'cyan', component: GlassWater, keywords: '喝水 纯净水 矿泉水 养生 补水 8杯水' },
  { value: 'Apple', label: '脆甜苹果', category: 'food', theme: 'emerald', component: Apple, keywords: '苹果 水果 维生素 减脂 健康 鲜果' },
  { value: 'Banana', label: '元气香蕉', category: 'food', theme: 'amber', component: Banana, keywords: '香蕉 水果 能量补给 运动减脂 早餐' },
  { value: 'Cherry', label: '车厘子大餐', category: 'food', theme: 'purple', component: Cherry, keywords: '车厘子 樱桃 水果 自由 鲜果 高档' },
  { value: 'Grape', label: '多汁紫提', category: 'food', theme: 'purple', component: Grape, keywords: '葡萄 紫提 阳光玫瑰 水果 果汁 甜' },
  { value: 'Citrus', label: '鲜榨橙汁', category: 'food', theme: 'amber', component: Citrus, keywords: '橙子 柠檬 柑橘 鲜榨果汁 维C' },
  { value: 'Egg', label: '新鲜鲜蛋', category: 'food', theme: 'amber', component: Egg, keywords: '鸡蛋 水煮蛋 优质蛋白 早餐 营养' },
  { value: 'EggFried', label: '金黄荷包蛋', category: 'food', theme: 'amber', component: EggFried, keywords: '荷包蛋 煎蛋 溏心蛋 早餐 蛋料理' },
  { value: 'Salad', label: '减脂沙拉', category: 'food', theme: 'emerald', component: Salad, keywords: '轻食 沙拉 低卡 低脂 健康餐 蔬菜' },
  { value: 'Wheat', label: '全麦燕麦', category: 'food', theme: 'amber', component: Wheat, keywords: '燕麦片 全麦面包 粗粮 杂粮 健康谷物' },
  { value: 'Nut', label: '每日坚果', category: 'food', theme: 'amber', component: Nut, keywords: '坚果 巴旦木 腰果 核桃 健康零食' },
  { value: 'Bean', label: '精选咖啡豆', category: 'food', theme: 'amber', component: Bean, keywords: '咖啡豆 原豆 烘焙 养生豆 磨粉' },
  { value: 'Carrot', label: '爽口胡萝卜', category: 'food', theme: 'amber', component: Carrot, keywords: '胡萝卜 蔬菜 减脂 维生素A 清爽' },
  { value: 'CookingPot', label: '养生砂锅煲', category: 'food', theme: 'amber', component: CookingPot, keywords: '砂锅 火锅 煲仔饭 炖鸡 烹饪 厨房' },
  { value: 'ChefHat', label: '私厨大作', category: 'food', theme: 'purple', component: ChefHat, keywords: '名厨 大厨厨艺 私房菜 亲自下厨 米其林' },
  { value: 'Refrigerator', label: '满载冰箱', category: 'food', theme: 'cyan', component: Refrigerator, keywords: '冰箱 零食库 冰饮 囤货 清凉 肥宅快乐水' },
  { value: 'Microwave', label: '深夜微波', category: 'food', theme: 'amber', component: Microwave, keywords: '微波炉 加热 热饭 夜宵 方便面 温暖' },
  { value: 'Martini', label: '格调鸡尾酒', category: 'food', theme: 'purple', component: Martini, keywords: '马天尼 鸡尾酒 酒吧 调酒 小酌 微醺' },
  { value: 'Milk', label: '香浓鲜奶', category: 'food', theme: 'cyan', component: Milk, keywords: '牛奶 鲜奶 早餐奶 拿铁 生椰拿铁' },
  { value: 'Dessert', label: '米其林甜点', category: 'food', theme: 'purple', component: Dessert, keywords: '法式甜点 甜品 下午茶 舒芙蕾 布丁' },
  { value: 'Store', label: '便利店扫货', category: 'food', theme: 'cyan', component: Store, keywords: '便利店 罗森 全家 711 零食扫荡' },
  { value: 'Ham', label: '金字火腿', category: 'food', theme: 'amber', component: Ham, keywords: '火腿 肉类 烤肉 熏肉 培根 西餐' },
  { value: 'Hop', label: '麦芽香气', category: 'food', theme: 'emerald', component: Hop, keywords: '啤酒花 麦芽 酿造 原浆 精酿啤酒' },
  { value: 'Gamepad2', label: '电竞手柄', category: 'digital', theme: 'purple', component: Gamepad2, keywords: '游戏手柄 steam switch ps5 xbox 主机游戏' },
  { value: 'Gamepad', label: '复古怀旧掌机', category: 'digital', theme: 'purple', component: Gamepad, keywords: '掌机 gba psp 游戏机 怀旧 童年' },
  { value: 'Headphones', label: '头戴降噪耳机', category: 'digital', theme: 'cyan', component: Headphones, keywords: '耳机 降噪 音乐 hifi 索尼 bose' },
  { value: 'Headset', label: '开黑对讲耳麦', category: 'digital', theme: 'purple', component: Headset, keywords: '电竞耳机 耳麦 连麦 语音 开黑 连招' },
  { value: 'Clapperboard', label: '院线首映大片', category: 'digital', theme: 'purple', component: Clapperboard, keywords: '电影 电影院 大片 淘票票 首映 观影' },
  { value: 'Film', label: '胶片复古风', category: 'digital', theme: 'purple', component: Film, keywords: '胶片 电影 胶卷 胶片相机 怀旧 艺术' },
  { value: 'Tv2', label: '智慧大屏', category: 'digital', theme: 'cyan', component: Tv2, keywords: '电视 4k 追剧 刷剧 连击 巨幕' },
  { value: 'Tv', label: '客厅影院', category: 'digital', theme: 'cyan', component: Tv, keywords: '电视机 客厅 家庭影院 综艺 剧集' },
  { value: 'BookOpen', label: '书香阅读', category: 'digital', theme: 'emerald', component: BookOpen, keywords: '读书 看书 kindle 阅读 小说 传记 文学' },
  { value: 'Book', label: '精装藏书', category: 'digital', theme: 'emerald', component: Book, keywords: '书籍 图书 购买新书 收藏 典籍 知识' },
  { value: 'BookMarked', label: '藏书签章', category: 'digital', theme: 'purple', component: BookMarked, keywords: '书签 标记 划重点 读书心得 收藏' },
  { value: 'Camera', label: '全画幅微单', category: 'digital', theme: 'cyan', component: Camera, keywords: '相机 摄影 拍照 采风 扫街 佳能 索尼' },
  { value: 'Smartphone', label: '旗舰新手机', category: 'digital', theme: 'cyan', component: Smartphone, keywords: '手机 iphone 苹果 安卓 换新机 科技' },
  { value: 'Laptop', label: '生产力笔记本', category: 'digital', theme: 'cyan', component: Laptop, keywords: '笔记本电脑 macbook 办公 轻薄本 换新' },
  { value: 'Monitor', label: '高刷电竞屏', category: 'digital', theme: 'purple', component: Monitor, keywords: '显示器 4k 144hz 桌面桌搭 大屏 超宽屏' },
  { value: 'MonitorSpeaker', label: '多媒体桌面音响', category: 'digital', theme: 'cyan', component: MonitorSpeaker, keywords: '音响 桌面音效 环绕声 电影感 低音' },
  { value: 'Watch', label: '智能健康腕表', category: 'digital', theme: 'emerald', component: Watch, keywords: '智能手表 applewatch 运动手环 电子表 穿戴' },
  { value: 'Music', label: '热门流行榜', category: 'digital', theme: 'purple', component: Music, keywords: '音乐 歌曲 网易云 qq音乐 新歌 听歌 专辑' },
  { value: 'Music2', label: '高雅交响乐', category: 'digital', theme: 'purple', component: Music2, keywords: '交响乐 钢琴曲 乐谱 旋律 古典乐 音符' },
  { value: 'Music3', label: '摇滚电吉他', category: 'digital', theme: 'purple', component: Music3, keywords: '摇滚 吉他 电声 现场 乐队 live' },
  { value: 'Music4', label: '民谣木吉他', category: 'digital', theme: 'amber', component: Music4, keywords: '民谣 木吉他 弹唱 尤克里里 扫弦' },
  { value: 'Radio', label: '深宵随身听', category: 'digital', theme: 'amber', component: Radio, keywords: '收音机 电台 播客 广播 fm 怀旧 晚安' },
  { value: 'RadioReceiver', label: '高级无线电台', category: 'digital', theme: 'purple', component: RadioReceiver, keywords: '电台 无线电 接收机 摩尔斯 专业音频' },
  { value: 'Mic', label: '唱响K歌房', category: 'digital', theme: 'amber', component: Mic, keywords: '麦克风 唱k ktv 全民k歌 练歌 唱歌 麦霸' },
  { value: 'Mic2', label: '播客专业录音', category: 'digital', theme: 'purple', component: Mic2, keywords: '主播 录音麦克风 声卡 配音 录音棚 播客' },
  { value: 'Video', label: '4K高清创作', category: 'digital', theme: 'cyan', component: Video, keywords: '拍视频 vlog 录像 b站 创作 剪辑 摄影' },
  { value: 'Dice1', label: '幸运单点骰', category: 'digital', theme: 'amber', component: Dice1, keywords: '骰子 摇色子 随机 幸运抽签 桌游点数' },
  { value: 'Dice2', label: '双人博弈骰', category: 'digital', theme: 'amber', component: Dice2, keywords: '双骰 桌游 掷骰 运气 幸运转盘' },
  { value: 'Dice5', label: '五福聚会桌游', category: 'digital', theme: 'amber', component: Dice5, keywords: '桌游 剧本杀 狼人杀 大富翁 聚会娱乐' },
  { value: 'Dice6', label: '满点幸运星', category: 'digital', theme: 'amber', component: Dice6, keywords: '骰子六点 大吉 大获全胜 幸运爆棚 通吃' },
  { value: 'Disc', label: '经典黑胶唱片', category: 'digital', theme: 'purple', component: Disc, keywords: '黑胶 唱片 cd 音乐发烧友 典藏 留声机' },
  { value: 'CassetteTape', label: '复古磁带卡带', category: 'digital', theme: 'amber', component: CassetteTape, keywords: '磁带 随身听 walkman 怀旧 80后 90后' },
  { value: 'Speaker', label: '重低音蓝牙音响', category: 'digital', theme: 'purple', component: Speaker, keywords: '音箱 蓝牙音响 jbl 漫步者 低音炮 环绕' },
  { value: 'BoomBox', label: '街潮手提音响', category: 'digital', theme: 'amber', component: BoomBox, keywords: '手提音箱 街舞 轰趴 潮流 户外放歌' },
  { value: 'Projector', label: '巨幕影院投影', category: 'digital', theme: 'cyan', component: Projector, keywords: '投影仪 极米 卧室巨幕 私人影院 投屏' },
  { value: 'Keyboard', label: '客制化机械键盘', category: 'digital', theme: 'purple', component: Keyboard, keywords: '键盘 机械轴 敲击感 键帽 客制化 码字' },
  { value: 'Mouse', label: '轻量电竞鼠标', category: 'digital', theme: 'cyan', component: Mouse, keywords: '鼠标 罗技 雷蛇 无线鼠标 电竞 顺滑' },
  { value: 'Tablet', label: '手绘数位板', category: 'digital', theme: 'cyan', component: Tablet, keywords: '平板 ipad 手绘板 绘画 画画 触控笔' },
  { value: 'Cpu', label: '超频旗舰芯片', category: 'digital', theme: 'purple', component: Cpu, keywords: '芯片 cpu 显卡 4090 极客 装机 核心' },
  { value: 'HardDrive', label: '海量高速硬盘', category: 'digital', theme: 'cyan', component: HardDrive, keywords: '硬盘 固态硬盘 移动硬盘 存储 备份 资料' },
  { value: 'Wifi', label: '千兆光纤满格', category: 'digital', theme: 'cyan', component: Wifi, keywords: 'wifi 宽带 5g 网速飞起 满格 冲浪 下载' },
  { value: 'Podcast', label: '沉浸式播客', category: 'digital', theme: 'purple', component: Podcast, keywords: '小宇宙 播客 访谈 对谈 治愈 倾听 慢聊' },
  { value: 'Drama', label: '震撼舞台戏剧', category: 'digital', theme: 'purple', component: Drama, keywords: '话剧 音乐剧 歌剧 现场 戏剧 人艺 沉浸' },
  { value: 'Ticket', label: '展演特权通票', category: 'digital', theme: 'cyan', component: Ticket, keywords: '门票 入场券 音乐节 演唱会 漫展 vip票' },
  { value: 'TicketPercent', label: '立减折扣券', category: 'digital', theme: 'amber', component: TicketPercent, keywords: '优惠券 抵用券 打折 减免 满减 特权' },
  { value: 'TicketCheck', label: '通关检票', category: 'digital', theme: 'emerald', component: TicketCheck, keywords: '验票 入场 成功核销 绿灯 畅通无阻' },
  { value: 'QrCode', label: '免密扫码凭证', category: 'digital', theme: 'cyan', component: QrCode, keywords: '二维码 扫一扫 兑换码 卡券核销 快捷' },
  { value: 'Barcode', label: '商品正品条码', category: 'digital', theme: 'cyan', component: Barcode, keywords: '条形码 扫码 专属商品 序列号 入库' },
  { value: 'Bot', label: 'AI超能小助理', category: 'digital', theme: 'cyan', component: Bot, keywords: '机器人 ai 大模型 科技 人工智能 体验' },
  { value: 'Joystick', label: '街机格斗摇杆', category: 'digital', theme: 'amber', component: Joystick, keywords: '街机 摇杆 拳皇 搓招 街机厅 怀旧' },
  { value: 'Swords', label: '竞技巅峰排位', category: 'digital', theme: 'purple', component: Swords, keywords: '排位 对决 pk 上分 决斗 晋级 胜利' },
  { value: 'Sword', label: '王者出征利剑', category: 'digital', theme: 'amber', component: Sword, keywords: '宝剑 剑 勇者 战斗 突破 装备 披荆斩棘' },
  { value: 'Shield', label: '全效守护盾甲', category: 'digital', theme: 'cyan', component: Shield, keywords: '盾牌 安全 防御 守护 保障 金钟罩' },
  { value: 'ShieldAlert', label: '安全警戒', category: 'digital', theme: 'amber', component: ShieldAlert, keywords: '防火墙 警戒 安全卫士 防御系统' },
  { value: 'BatteryCharging', label: '急速回血快充', category: 'digital', theme: 'emerald', component: BatteryCharging, keywords: '充电 闪充 满电 能量 充电宝 续航' },
  { value: 'BatteryFull', label: '百分百满电量', category: 'digital', theme: 'emerald', component: BatteryFull, keywords: '满电 续航持久 电量十足 状态饱满 安全感' },
  { value: 'Bell', label: '心愿提醒铃铛', category: 'digital', theme: 'amber', component: Bell, keywords: '铃铛 提醒 闹铃 通知 关注 消息 提醒' },
  { value: 'Airplay', label: '跨屏无线投放', category: 'digital', theme: 'cyan', component: Airplay, keywords: '投屏 隔空播放 互联 无线连接 扩展屏' },
  { value: 'Bluetooth', label: '蓝牙瞬时秒连', category: 'digital', theme: 'cyan', component: Bluetooth, keywords: '蓝牙 配对 耳机手柄 秒连 极速 无线' },
  { value: 'Cast', label: '电视无线串流', category: 'digital', theme: 'cyan', component: Cast, keywords: '串流 投屏 镜像 多端互动 大屏分享' },
  { value: 'Blocks', label: '乐高积木拼搭', category: 'digital', theme: 'amber', component: Blocks, keywords: '积木 乐高 拼装 搭建 创造力 模块化 动手' },
  { value: 'Fingerprint', label: '专属指纹印记', category: 'digital', theme: 'cyan', component: Fingerprint, keywords: '指纹 唯一 专属 认证 安全 密码 独一无二' },
  { value: 'Scan', label: '扫码验真识别', category: 'digital', theme: 'cyan', component: Scan, keywords: '扫描 识图 识别 科技 敏锐 洞察 快速' },
  { value: 'Contrast', label: '分明黑白对比', category: 'digital', theme: 'purple', component: Contrast, keywords: '对比 调色 明暗 审美 纯粹 极简 艺术感' },
  { value: 'Bike', label: '碳纤维公路车', category: 'leisure', theme: 'emerald', component: Bike, keywords: '骑行 自行车 公路车 户外 环湖 破风 刷街' },
  { value: 'Dumbbell', label: '硬核大重量哑铃', category: 'leisure', theme: 'amber', component: Dumbbell, keywords: '哑铃 健身 撸铁 卧推 力量训练 增肌 塑形' },
  { value: 'BicepsFlexed', label: '饱满肱二头肌', category: 'leisure', theme: 'amber', component: BicepsFlexed, keywords: '肌肉 健美 力量 强壮 训练 体魄' },
  { value: 'Footprints', label: '万步轻快漫步', category: 'leisure', theme: 'emerald', component: Footprints, keywords: '徒步 散步 慢跑 健走 万步 减脂 丈量城市' },
  { value: 'Plane', label: '环球跨洲旅行', category: 'leisure', theme: 'cyan', component: Plane, keywords: '飞机 机票 航班 远行 旅行 出境游 探索世界' },
  { value: 'PlaneTakeoff', label: '振翅高飞启程', category: 'leisure', theme: 'cyan', component: PlaneTakeoff, keywords: '起飞 启程 出发 奔赴山海 旅程开启 航班' },
  { value: 'PlaneLanding', label: '平安平安着陆', category: 'leisure', theme: 'emerald', component: PlaneLanding, keywords: '降落 到达 抵达 归巢 目的地 踏上新土地' },
  { value: 'Luggage', label: '轻便万向轮箱', category: 'leisure', theme: 'amber', component: Luggage, keywords: '行李箱 整理行装 度假 周末出游 拖箱走天下' },
  { value: 'Car', label: '自驾驰骋跑车', category: 'leisure', theme: 'cyan', component: Car, keywords: '自驾 开车 跑车 兜风 租车 沿海公路 驰骋' },
  { value: 'CarTaxiFront', label: '商务优享专车', category: 'leisure', theme: 'cyan', component: CarTaxiFront, keywords: '专车 礼宾 接送机 舒适出行 打车 免疲惫' },
  { value: 'Caravan', label: '舒适房车旅行', category: 'leisure', theme: 'amber', component: Caravan, keywords: '房车 露营 自驾游 移动城堡 随处安家' },
  { value: 'Train', label: '极速高铁动车', category: 'leisure', theme: 'cyan', component: Train, keywords: '高铁 动车 火车 绿皮车 周边城际 双城度假' },
  { value: 'TrainFront', label: '复兴号新干线', category: 'leisure', theme: 'cyan', component: TrainFront, keywords: '高铁 车头 飞驰 铁路 穿越山川 速度之旅' },
  { value: 'Ship', label: '五星海上游轮', category: 'leisure', theme: 'cyan', component: Ship, keywords: '游轮 豪华大船 出海 航海 游艇 海上度假 甲板' },
  { value: 'ShipWheel', label: '执掌航海舵手', category: 'leisure', theme: 'cyan', component: ShipWheel, keywords: '船舵 航海 舵手 远洋 破浪 前进' },
  { value: 'Sailboat', label: '破浪白帆游艇', category: 'leisure', theme: 'cyan', component: Sailboat, keywords: '帆船 扬帆 航行 帆板 水上运动 乘风破浪' },
  { value: 'Palmtree', label: '热带椰林沙滩', category: 'leisure', theme: 'cyan', component: Palmtree, keywords: '海岛 三亚 普吉 椰树 沙滩 日落 碧海蓝天' },
  { value: 'Tent', label: '野趣天幕露营', category: 'leisure', theme: 'emerald', component: Tent, keywords: '帐篷 露营 围炉煮茶 篝火 野餐 户外生活' },
  { value: 'TentTree', label: '林间隐逸露营', category: 'leisure', theme: 'emerald', component: TentTree, keywords: '露营 森林营地 木屋 自然庇护所 秘境' },
  { value: 'Mountain', label: '登高绝顶峰峦', category: 'leisure', theme: 'emerald', component: Mountain, keywords: '爬山 登山 远足 自然 登顶 览众山小 徒步峰' },
  { value: 'MountainSnow', label: '银白滑雪天堂', category: 'leisure', theme: 'cyan', component: MountainSnow, keywords: '雪山 单板 双板 滑雪 崇礼 长白山 冬季运动' },
  { value: 'MapPin', label: '热门地标打卡', category: 'leisure', theme: 'purple', component: MapPin, keywords: '地标 探店 打卡 定位 坐标 签到 到此一游' },
  { value: 'MapPinCheck', label: '完成打卡盖章', category: 'leisure', theme: 'emerald', component: MapPinCheck, keywords: '打卡成功 通关 盖章 达成 踩点成功' },
  { value: 'Map', label: '独家旅行路书', category: 'leisure', theme: 'amber', component: Map, keywords: '地图 自驾路线 攻略 轨迹 行程指南 指引' },
  { value: 'Compass', label: '精密指南罗盘', category: 'leisure', theme: 'cyan', component: Compass, keywords: '指南针 罗盘 方向 探险 辨位 户外求生 不迷路' },
  { value: 'Sun', label: '灿烂明媚艳阳', category: 'leisure', theme: 'amber', component: Sun, keywords: '阳光 晴空 日光浴 温暖 紫外线 活力满满 晴天' },
  { value: 'SunMedium', label: '和煦微风和阳', category: 'leisure', theme: 'amber', component: SunMedium, keywords: '和煦 暖阳 踏青 春游 天气极佳 散心 舒畅' },
  { value: 'Sunrise', label: '壮丽山巅日出', category: 'leisure', theme: 'amber', component: Sunrise, keywords: '日出 朝阳 破晓 晨光 晨曦 希望' },
  { value: 'Sunset', label: '橘粉晚霞落日', category: 'leisure', theme: 'amber', component: Sunset, keywords: '日落 晚霞 夕阳 浪漫 傍晚 橘红黄昏' },
  { value: 'Moon', label: '静谧无眠深宵', category: 'leisure', theme: 'purple', component: Moon, keywords: '月亮 夜晚 安睡 休息 晚安 早点睡 沉睡 宁静' },
  { value: 'MoonStar', label: '璀璨星月夜空', category: 'leisure', theme: 'purple', component: MoonStar, keywords: '星空 夜空 浪漫 许愿 守夜 银河 露宿' },
  { value: 'Bed', label: '云朵软弹大床', category: 'leisure', theme: 'purple', component: Bed, keywords: '大床 软榻 赖床 睡懒觉 优质睡眠 纯棉 无拘无束' },
  { value: 'BedDouble', label: '五星奢华套房', category: 'leisure', theme: 'purple', component: BedDouble, keywords: '双人床 豪华酒店 宾馆 民宿 行政套房 度假' },
  { value: 'Bath', label: '芳香私汤温泉', category: 'leisure', theme: 'cyan', component: Bath, keywords: '泡澡 浴缸 温泉 私汤 洗去疲惫 放松水疗 spa' },
  { value: 'ShowerHead', label: '痛快暴汗淋浴', category: 'leisure', theme: 'cyan', component: ShowerHead, keywords: '洗澡 花洒 淋浴 冲凉 清爽 热水澡 卸下疲惫' },
  { value: 'AlarmClock', label: '自律晨光闹钟', category: 'leisure', theme: 'cyan', component: AlarmClock, keywords: '闹钟 早起 打卡 晨跑 晨读 规律作息 元气清晨' },
  { value: 'Activity', label: '运动能量峰值', category: 'leisure', theme: 'emerald', component: Activity, keywords: '活力 心肺 运动量 达标 能量燃烧 活力四射' },
  { value: 'HeartPulse', label: '心率体能监测', category: 'leisure', theme: 'purple', component: HeartPulse, keywords: '心跳 脉搏 心率 有氧运动 燃脂 运动健康' },
  { value: 'Timer', label: '高配速秒表', category: 'leisure', theme: 'cyan', component: Timer, keywords: '计时器 跑表 番茄钟 间歇跑 配速 训练冲刺' },
  { value: 'Scale', label: '完美体态称重', category: 'leisure', theme: 'emerald', component: Scale, keywords: '体脂秤 称重 塑形 减重成功 黄金身材 达标' },
  { value: 'Pill', label: '每日维生素片', category: 'leisure', theme: 'cyan', component: Pill, keywords: '维生素 补剂 鱼油 钙片 养生保健 补充能量' },
  { value: 'Trophy', label: '赛事捧杯荣耀', category: 'leisure', theme: 'amber', component: Trophy, keywords: '冠军 奖杯 第一名 捧杯 赛事胜利 巅峰荣耀' },
  { value: 'Medal', label: '金牌勋章挂胸', category: 'leisure', theme: 'amber', component: Medal, keywords: '马拉松 奖牌 勋章 完赛纪念 荣誉 登台领奖' },
  { value: 'Flag', label: '冲过终点胜旗', category: 'leisure', theme: 'amber', component: Flag, keywords: '终点线 胜利旗帜 里程碑 插旗 誓师 达成目标' },
  { value: 'Anchor', label: '安心避风港湾', category: 'leisure', theme: 'cyan', component: Anchor, keywords: '铁锚 港口 停靠 避风港 稳固 踏实 归航' },
  { value: 'Waves', label: '清凉破浪狂潮', category: 'leisure', theme: 'cyan', component: Waves, keywords: '海浪 冲浪 游泳 嬉水 水上乐园 清凉一夏' },
  { value: 'Trees', label: '郁郁葱葱绿林', category: 'leisure', theme: 'emerald', component: Trees, keywords: '森林 树木 氧吧 吸氧 大自然 森林浴 徒步' },
  { value: 'TreePine', label: '常青高耸针叶', category: 'leisure', theme: 'emerald', component: TreePine, keywords: '松树 常青 针叶林 森林 苍翠 露营木屋' },
  { value: 'Bus', label: '环景观光巴士', category: 'leisure', theme: 'cyan', component: Bus, keywords: '观光巴士 双层巴士 大巴 周边游 随上随下' },
  { value: 'Navigation', label: '智能寻路罗盘', category: 'leisure', theme: 'cyan', component: Navigation, keywords: '导航 罗盘 寻路 循迹 GPS 方向指引 前行' },
  { value: 'Fuel', label: '加满油箱启程', category: 'leisure', theme: 'amber', component: Fuel, keywords: '加油 95加满 充电桩 续航里程 动力澎湃 出发' },
  { value: 'Zap', label: '电量百分百爆格', category: 'leisure', theme: 'amber', component: Zap, keywords: '闪电 动力 满血复活 能量爆棚 激情四射' },
  { value: 'Globe', label: '连通全球视野', category: 'leisure', theme: 'cyan', component: Globe, keywords: '地球 世界 全球 国际化 视野 远方 环球' },
  { value: 'Earth', label: '守护美丽蔚蓝', category: 'leisure', theme: 'emerald', component: Earth, keywords: '地球家园 自然 环保 广阔 环球 宇宙' },
  { value: 'Send', label: '纸飞机发心声', category: 'leisure', theme: 'cyan', component: Send, keywords: '纸飞机 寄信 发送 传达 寄托 畅想 希望' },
  { value: 'LifeBuoy', label: '救生救急锦囊', category: 'leisure', theme: 'amber', component: LifeBuoy, keywords: '救生圈 护航 救急 保障 逢凶化吉 帮助' },
  { value: 'Gauge', label: '仪表盘最高转速', category: 'leisure', theme: 'amber', component: Gauge, keywords: '速度 仪表 满速 冲刺 激情 动能 狂飙' },
  { value: 'Helicopter', label: '空中鸟瞰直升机', category: 'leisure', theme: 'cyan', component: Helicopter, keywords: '直升机 低空飞行 鸟瞰 俯瞰 航拍 翱翔' },
  { value: 'Hotel', label: '奢华度假酒店', category: 'leisure', theme: 'purple', component: Hotel, keywords: '星级酒店 度假村 宾馆 尊享 奢华 住宿' },
  { value: 'Castle', label: '古堡神秘探幽', category: 'leisure', theme: 'purple', component: Castle, keywords: '古堡 探索 欧式 华美 历史 漫游 遗迹' },
  { value: 'Gift', label: '心愿梦幻礼盒', category: 'reward', theme: 'purple', component: Gift, keywords: '礼物 礼品 礼盒 伴手礼 惊喜 送给自己 犒劳' },
  { value: 'Crown', label: '王者至尊皇冠', category: 'reward', theme: 'amber', component: Crown, keywords: '皇冠 国王 女王 尊贵 头号 专属特权 巅峰' },
  { value: 'Gem', label: '流光溢彩珠宝', category: 'reward', theme: 'purple', component: Gem, keywords: '宝石 珠宝 钻石 项链 戒指 奢侈品 璀璨光华' },
  { value: 'Diamond', label: '八心八箭美钻', category: 'reward', theme: 'cyan', component: Diamond, keywords: '钻石 裸钻 恒久 闪耀 珍藏 奢华 闪亮' },
  { value: 'ShoppingBag', label: '大牌专柜提袋', category: 'reward', theme: 'purple', component: ShoppingBag, keywords: '购物袋 买买买 逛街 专柜 商场 扫货 战利品' },
  { value: 'ShoppingCart', label: '一键清空购物车', category: 'reward', theme: 'cyan', component: ShoppingCart, keywords: '购物车 清空 淘宝 京东 网购 囤货 剁手' },
  { value: 'ShoppingBasket', label: '装满超市提篮', category: 'reward', theme: 'emerald', component: ShoppingBasket, keywords: '超市 购物篮 零食 生鲜 水果 采购日' },
  { value: 'Tag', label: '限时特惠吊牌', category: 'reward', theme: 'amber', component: Tag, keywords: '标签 优惠 折扣 大促 秒杀 降价 吊牌' },
  { value: 'Tags', label: '多重组合优惠', category: 'reward', theme: 'amber', component: Tags, keywords: '多标签 标签组 满减 叠券 超划算 活动' },
  { value: 'BadgePercent', label: 'VIP独享折上折', category: 'reward', theme: 'amber', component: BadgePercent, keywords: '折扣 百分比 优惠券 折扣率 特权 会员价' },
  { value: 'BadgeDollarSign', label: '尊享金牌返现', category: 'reward', theme: 'amber', component: BadgeDollarSign, keywords: '返现 现金券 优惠 会员权益 红包到账' },
  { value: 'BadgeCheck', label: '官方正品金标', category: 'reward', theme: 'emerald', component: BadgeCheck, keywords: '官方认证 验真 正品保真 优选品质 权威' },
  { value: 'Key', label: '通关纯金密匙', category: 'reward', theme: 'amber', component: Key, keywords: '金钥匙 开启 解锁 密钥 特权 房门钥匙' },
  { value: 'KeyRound', label: '密室通关印鉴', category: 'reward', theme: 'cyan', component: KeyRound, keywords: '圆匙 密匙 隐藏关卡 开启宝箱 破解密码' },
  { value: 'Package', label: '惊喜盲盒拆箱', category: 'reward', theme: 'amber', component: Package, keywords: '快递 包裹 盲盒 开盲盒 期待感 拆箱 宝箱' },
  { value: 'PackageOpen', label: '开箱高光揭秘', category: 'reward', theme: 'amber', component: PackageOpen, keywords: '开箱 揭晓 验货 战利品 喜悦 拆包裹' },
  { value: 'PackageCheck', label: '包裹稳妥送达', category: 'reward', theme: 'emerald', component: PackageCheck, keywords: '签收 妥投 快递到家 完美无损 心安' },
  { value: 'Wand2', label: '愿望实现仙女棒', category: 'reward', theme: 'purple', component: Wand2, keywords: '仙女棒 魔法 许愿 奇迹 成真 变美 特权' },
  { value: 'Coins', label: '满满一袋金币', category: 'reward', theme: 'amber', component: Coins, keywords: '金币 零花钱 红包 奖金 金库 压岁钱 财富' },
  { value: 'Wallet', label: '鼓鼓真皮钱包', category: 'reward', theme: 'amber', component: Wallet, keywords: '钱包 皮夹 现金卡片 财富增长 资产充沛 预算' },
  { value: 'WalletCards', label: '多卡位卡包', category: 'reward', theme: 'cyan', component: WalletCards, keywords: '卡包 银行卡 会员卡 门禁卡 收纳 精致' },
  { value: 'CreditCard', label: '无限畅刷黑卡', category: 'reward', theme: 'cyan', component: CreditCard, keywords: '黑卡 信用卡 畅刷 随心 支付 自由消费' },
  { value: 'Banknote', label: '厚厚一沓钞票', category: 'reward', theme: 'emerald', component: Banknote, keywords: '钞票 现金 纸币 稿费 奖金 分红 收入' },
  { value: 'PiggyBank', label: '元气攒钱小猪', category: 'reward', theme: 'amber', component: PiggyBank, keywords: '存钱罐 攒钱 小猪 储蓄 理财 积少成多 收益' },
  { value: 'Heart', label: '对自己好一点', category: 'reward', theme: 'purple', component: Heart, keywords: '爱心 心意 宠爱自己 治愈 温柔 关怀 快乐' },
  { value: 'HeartHandshake', label: '真挚合作相拥', category: 'reward', theme: 'emerald', component: HeartHandshake, keywords: '握手 感谢 约定 承诺 伙伴 合作 信任' },
  { value: 'Smile', label: '生活处处欢笑', category: 'reward', theme: 'amber', component: Smile, keywords: '笑脸 开心 快乐 好心情 积极 阳光 治愈' },
  { value: 'SmilePlus', label: '快乐加倍绽放', category: 'reward', theme: 'amber', component: SmilePlus, keywords: '超级开心 喜上加喜 惊喜连连 乐开怀 情绪价值' },
  { value: 'Laugh', label: '开怀拍手捧腹', category: 'reward', theme: 'amber', component: Laugh, keywords: '大笑 欢聚 欢乐 幽默 捧腹 乐开花 放松' },
  { value: 'PartyPopper', label: '狂欢漫天拉炮', category: 'reward', theme: 'purple', component: PartyPopper, keywords: '礼花 拉炮 派对 狂欢 庆祝 庆祝日 恭喜' },
  { value: 'Shirt', label: '换季时尚新装', category: 'reward', theme: 'emerald', component: Shirt, keywords: '衣服 衬衫 卫衣 潮牌 穿搭 换季 时尚 剪裁' },
  { value: 'Glasses', label: '明星同款墨镜', category: 'reward', theme: 'cyan', component: Glasses, keywords: '墨镜 太阳镜 眼镜 造型 时尚 潮人 护目' },
  { value: 'Flower2', label: '娇艳盛开玫瑰', category: 'reward', theme: 'purple', component: Flower2, keywords: '玫瑰 鲜花 花束 郁金香 浪漫 仪式感 赠花' },
  { value: 'Flower', label: '向阳明亮葵花', category: 'reward', theme: 'amber', component: Flower, keywords: '向日葵 太阳花 生机 积极 向阳 明朗 鲜花' },
  { value: 'Palette', label: '灵感缤纷画盘', category: 'reward', theme: 'purple', component: Palette, keywords: '调色盘 颜料 艺术 美术 创意 灵感 绘画 绘画' },
  { value: 'Brush', label: '细腻羊毛彩妆刷', category: 'reward', theme: 'purple', component: Brush, keywords: '化妆刷 笔刷 彩妆 美妆 护肤 描摹 妆容' },
  { value: 'Scissors', label: '总监剪裁造型', category: 'reward', theme: 'cyan', component: Scissors, keywords: '理发 剪刀 发型设计 剪发 造型 toni 美发' },
  { value: 'HandMetal', label: '摇滚热血手势', category: 'reward', theme: 'purple', component: HandMetal, keywords: '摇滚 手势 现场 live 躁动 青年节 狂欢' },
  { value: 'Inbox', label: '投递心愿信箱', category: 'reward', theme: 'cyan', component: Inbox, keywords: '收件箱 愿望箱 投递 信件 留言 收集 珍藏' },
  { value: 'ShieldCheck', label: '七天无忧质保', category: 'reward', theme: 'emerald', component: ShieldCheck, keywords: '保障 官方 认证 质保 放心买 品质承诺' },
  { value: 'Receipt', label: '安心消费清单', category: 'reward', theme: 'cyan', component: Receipt, keywords: '小票 账单 发票 消费记录 凭证 回执 清晰' },
  { value: 'ReceiptText', label: '明细清晰票据', category: 'reward', theme: 'cyan', component: ReceiptText, keywords: '详细账单 明细 单据 对账单 消费凭证' },
  { value: 'Sparkle', label: '万众瞩目星光', category: 'reward', theme: 'amber', component: Sparkle, keywords: '星星 闪耀 高光 心愿 独一无二 璀璨聚焦' },
  { value: 'Star', label: '五角愿望之星', category: 'reward', theme: 'amber', component: Star, keywords: '五角星 许愿 星星 奖励 荣誉 优胜 闪光' },
  { value: 'ThumbsUp', label: '点赞称赞', category: 'reward', theme: 'amber', component: ThumbsUp, keywords: '点赞 赞 夸奖 棒 认可 认同' },
  { value: 'ThumbsDown', label: '果断拒绝', category: 'reward', theme: 'purple', component: ThumbsDown, keywords: '拒绝 倒赞 不喜欢 说不 勇气 设立边界' },
  { value: 'HandCoins', label: '打赏犒劳', category: 'reward', theme: 'amber', component: HandCoins, keywords: '打赏 赠金 红包 酬劳 付出 报酬' },
  { value: 'HandHeart', label: '手心温情', category: 'reward', theme: 'purple', component: HandHeart, keywords: '爱心 关怀 温暖 给予 慈善 善意 治愈' },
  { value: 'Sparkles', label: '闪烁奇迹', category: 'reward', theme: 'amber', component: Sparkles, keywords: '魔法 奇迹 闪光 闪耀 高光时刻 惊喜' },
  { value: 'Truck', label: '大件运输直达', category: 'reward', theme: 'amber', component: Truck, keywords: '货车 运输 搬家 乔迁 采购 顺丰 送达' },
  { value: 'Stamp', label: '通关圆满印章', category: 'reward', theme: 'amber', component: Stamp, keywords: '印章 盖印 通关 认证 盖章 纪念 毕业 准许' },
  { value: 'Ribbon', label: '荣誉表彰缎带', category: 'reward', theme: 'purple', component: Ribbon, keywords: '丝带 勋带 荣誉 礼遇 典雅 嘉奖 典礼' },
  { value: 'Vault', label: '重金保险库金库', category: 'reward', theme: 'amber', component: Vault, keywords: '保险柜 金库 保管 资产 安全 财富 储备' },
  { value: 'Home', label: '温暖避风小家', category: 'home', theme: 'amber', component: Home, keywords: '家 温馨 小家 归属 避风港 居家 舒适 港湾' },
  { value: 'House', label: '独栋田园小楼', category: 'home', theme: 'amber', component: House, keywords: '别墅 独栋 小洋楼 宁静 田园 归隐 理想家园' },
  { value: 'Sofa', label: '葛优躺深陷沙发', category: 'home', theme: 'purple', component: Sofa, keywords: '沙发 休息 躺平 追剧 客厅 慵懒 靠枕 放松' },
  { value: 'Armchair', label: '沉浸单人扶手椅', category: 'home', theme: 'amber', component: Armchair, keywords: '单人椅 扶手椅 读书角 独处 静谧 包裹感' },
  { value: 'Lamp', label: '伴读柔光台灯', category: 'home', theme: 'amber', component: Lamp, keywords: '台灯 夜灯 灯光 暖光 伴读 睡前 护眼 温馨' },
  { value: 'LampCeiling', label: '明亮温馨吊灯', category: 'home', theme: 'amber', component: LampCeiling, keywords: '吊灯 客厅灯 餐厅灯 照亮 室内 氛围感 家装' },
  { value: 'LampDesk', label: '工作专属桌面灯', category: 'home', theme: 'cyan', component: LampDesk, keywords: '台灯 桌面 护眼台灯 专注 办公灯 照亮桌子' },
  { value: 'WashingMachine', label: '阳光香气洗衣机', category: 'home', theme: 'cyan', component: WashingMachine, keywords: '洗衣机 洗衣服 干净 烘干 阳光香气 洁净' },
  { value: 'Trash2', label: '大快人心断舍离', category: 'home', theme: 'emerald', component: Trash2, keywords: '垃圾桶 断舍离 清理 丢弃 轻松 极简 扫除' },
  { value: 'Clock', label: '静止的悠闲时光', category: 'home', theme: 'cyan', component: Clock, keywords: '时钟 时间 放慢 漫步 自由安排 不慌不忙 沉淀' },
  { value: 'Hourglass', label: '沙漏静坐冥想', category: 'home', theme: 'amber', component: Hourglass, keywords: '沙漏 时间流淌 冥想 专注 放空 沉思 呼吸' },
  { value: 'BookHeart', label: '睡前治愈读本', category: 'home', theme: 'purple', component: BookHeart, keywords: '治愈 心灵 温暖 睡前读物 心理学 慰藉 疗愈' },
  { value: 'Bird', label: '灵动啁啾雀鸟', category: 'home', theme: 'cyan', component: Bird, keywords: '鸟 鹦鹉 雀鸟 鸣叫 灵动 生机 鸣叫 自然之声' },
  { value: 'Leaf', label: '净化室内绿植', category: 'home', theme: 'emerald', component: Leaf, keywords: '树叶 绿植 龟背竹 散尾葵 养眼 净化空气' },
  { value: 'Sprout', label: '破土新绿幼苗', category: 'home', theme: 'emerald', component: Sprout, keywords: '嫩芽 幼苗 种子 萌芽 希望 种植 养成 生命' },
  { value: 'TreeDeciduous', label: '庭院沙沙微风', category: 'home', theme: 'emerald', component: TreeDeciduous, keywords: '庭院 树木 乘凉 惬意 摇曳 风光 乘凉 清新' },
  { value: 'CloudRain', label: '听雨助眠白噪音', category: 'home', theme: 'cyan', component: CloudRain, keywords: '下雨 雨声 白噪音 助眠 窗外 舒适 阴雨天 惬意' },
  { value: 'Snowflake', label: '围炉观赏初雪', category: 'home', theme: 'cyan', component: Snowflake, keywords: '雪花 初雪 冬日 暖气 围炉 暖洋洋 白雪皑皑' },
  { value: 'SunDim', label: '午后窗边树荫', category: 'home', theme: 'amber', component: SunDim, keywords: '树荫 柔和阳光 午后 小憩 片刻 惬意 茶歇' },
  { value: 'Cat', label: '呼噜软萌喵星人', category: 'home', theme: 'amber', component: Cat, keywords: '猫 猫咪 撸猫 喵星人 软萌 陪伴 咕噜 吸猫' },
  { value: 'Dog', label: '摇尾欢腾汪星人', category: 'home', theme: 'amber', component: Dog, keywords: '狗 狗狗 遛狗 汪星人 欢快 跑步 陪伴 飞盘' },
  { value: 'Rabbit', label: '毛绒温顺小兔', category: 'home', theme: 'purple', component: Rabbit, keywords: '兔子 萌宠 毛茸茸 温顺 垂耳兔 可爱 治愈' },
  { value: 'Squirrel', label: '林间灵巧松鼠', category: 'home', theme: 'amber', component: Squirrel, keywords: '松鼠 森林 灵巧 藏坚果 自然 萌趣 生动' },
  { value: 'Clover', label: '罕见四叶幸运草', category: 'home', theme: 'emerald', component: Clover, keywords: '四叶草 幸运 锦鲤 绿植 幸运常伴 好运吉祥' },
  { value: 'Rainbow', label: '雨后斑斓彩虹', category: 'home', theme: 'purple', component: Rainbow, keywords: '彩虹 七彩 雨过天晴 奇迹 壮观 幸运 祥瑞' },
  { value: 'CloudSun', label: '微风半晴晴天', category: 'home', theme: 'amber', component: CloudSun, keywords: '多云转晴 微风 舒适天气 散心 出行 惬意好日' },
  { value: 'Umbrella', label: '雨中漫步撑伞', category: 'home', theme: 'cyan', component: Umbrella, keywords: '雨伞 遮阳 遮雨 漫步 浪漫 挡风遮雨 安全感' },
  { value: 'Wind', label: '山谷清凉穿堂风', category: 'home', theme: 'cyan', component: Wind, keywords: '微风 凉风 自然风 清爽 拂面 空气流通 惬意' },
  { value: 'Church', label: '静心礼拜教堂', category: 'home', theme: 'amber', component: Church, keywords: '教堂 钟声 静谧 虔诚 仪式感 婚礼 庄严' },
  { value: 'HeartCrack', label: '碎裂心痛治愈', category: 'home', theme: 'purple', component: HeartCrack, keywords: '心碎 疗伤 走出低谷 重获新生 治愈 坚强' },
  { value: 'DoorOpen', label: '推开未知之门', category: 'home', theme: 'cyan', component: DoorOpen, keywords: '开门 迎客 新世界 迈出一步 新旅程 启程' },
  { value: 'DoorClosed', label: '闭门专属空间', category: 'home', theme: 'purple', component: DoorClosed, keywords: '独处 免打扰 私密 安全感 静心 闭关' },
  { value: 'ShieldBan', label: '隔绝外界纷扰', category: 'home', theme: 'purple', component: ShieldBan, keywords: '屏蔽 拒绝打扰 专注 独处 结界 保护 防护' },
  { value: 'FlameKindling', label: '温暖壁炉柴火', category: 'home', theme: 'amber', component: FlameKindling, keywords: '篝火 柴火 壁炉 围炉 温暖 炉火 疗愈' },
  { value: 'SunMoon', label: '日夜流转不息', category: 'home', theme: 'purple', component: SunMoon, keywords: '日月 晨昏 昼夜 自然节律 规律 作息 和谐' },
  { value: 'Thermometer', label: '舒适适宜温度', category: 'home', theme: 'cyan', component: Thermometer, keywords: '温度 宜居 舒适 恒温 26度 适宜 春意' },
  { value: 'Droplet', label: '甘露润物无声', category: 'home', theme: 'cyan', component: Droplet, keywords: '水滴 滋润 灵动 纯净 清爽 晨露 汇聚成海' },
  { value: 'GraduationCap', label: '戴上学士学位帽', category: 'study', theme: 'purple', component: GraduationCap, keywords: '毕业 学位 考研 考公 上岸 证书 学业有成' },
  { value: 'School', label: '重返静谧学堂', category: 'study', theme: 'amber', component: School, keywords: '学校 学堂 课堂 进修 培训 充电 校园生活' },
  { value: 'Library', label: '图书馆沉浸自习', category: 'study', theme: 'emerald', component: Library, keywords: '图书馆 阅览室 自习室 沉浸 墨香 知识殿堂' },
  { value: 'BookCopy', label: '海量学术藏书', category: 'study', theme: 'emerald', component: BookCopy, keywords: '学术 资料 专著 典藏 知识体系 文库 累积' },
  { value: 'BookOpenCheck', label: '全书研读通关', category: 'study', theme: 'emerald', component: BookOpenCheck, keywords: '精读 读完 书目打卡 通读 吸收 融会贯通' },
  { value: 'Bookmark', label: '高亮记忆书签', category: 'study', theme: 'purple', component: Bookmark, keywords: '书签 重点 划线 精华 摘录 记忆 标记' },
  { value: 'PenTool', label: '矢量视觉设计', category: 'study', theme: 'purple', component: PenTool, keywords: '设计 矢量 钢笔工具 创意 ui 插画 ps 审美' },
  { value: 'Pencil', label: '灵感随笔手绘', category: 'study', theme: 'amber', component: Pencil, keywords: '铅笔 随记 涂鸦 素描 构思 原型 草图记录' },
  { value: 'PencilRuler', label: '精密工程测绘', category: 'study', theme: 'cyan', component: PencilRuler, keywords: '尺子 制图 结构 比例 精准 严谨 规范' },
  { value: 'Highlighter', label: '重点荧光批注', category: 'study', theme: 'amber', component: Highlighter, keywords: '荧光笔 划重点 备考 复习 核心提炼 考点' },
  { value: 'Eraser', label: '纠错重来橡皮', category: 'study', theme: 'amber', component: Eraser, keywords: '橡皮 擦除 纠错 优化 迭代 重新出发 调整' },
  { value: 'FileCode', label: '纯净代码源码', category: 'study', theme: 'cyan', component: FileCode, keywords: '编程 源代码 程序 开发 算法 前端 后端' },
  { value: 'FileCode2', label: '多语言项目集', category: 'study', theme: 'cyan', component: FileCode2, keywords: '项目工程 脚本 编译 自动化 跨平台 源码' },
  { value: 'Code', label: '极客算法攻坚', category: 'study', theme: 'cyan', component: Code, keywords: '代码 html js py 算法 架构 难题攻关 解决bug' },
  { value: 'Terminal', label: '黑客黑底终端', category: 'study', theme: 'purple', component: Terminal, keywords: '命令行 终端 linux bash 部署 运维 极客黑客' },
  { value: 'Database', label: '高并发分布式库', category: 'study', theme: 'cyan', component: Database, keywords: '数据库 sql 数据建模 数据资产 存储 高并发' },
  { value: 'Lightbulb', label: '惊艳灵感破局', category: 'study', theme: 'amber', component: Lightbulb, keywords: '灯泡 创意 灵光一闪 脑洞 点子 策划 破局' },
  { value: 'Brain', label: '极智深度思维', category: 'study', theme: 'purple', component: Brain, keywords: '大脑 思考 认知 逻辑 智慧 决策 洞察力 战略' },
  { value: 'Target', label: '正中十环标靶', category: 'study', theme: 'purple', component: Target, keywords: '目标 靶心 命中 达标 okr kpi 达成使命 聚焦' },
  { value: 'Crosshair', label: '心流无扰准星', category: 'study', theme: 'cyan', component: Crosshair, keywords: '准星 极致专注 深度工作 心流 排除干扰 聚焦' },
  { value: 'Rocket', label: '飞跃破圈火箭', category: 'study', theme: 'purple', component: Rocket, keywords: '火箭 跃迁 爆发 飞跃 突破 效率狂飙 升空' },
  { value: 'Award', label: '卓越金质奖章', category: 'study', theme: 'amber', component: Award, keywords: '奖项 奖状 表彰 资质 荣誉感 官方认证 嘉奖' },
  { value: 'Presentation', label: '全场掌声提案', category: 'study', theme: 'cyan', component: Presentation, keywords: '演讲 汇报 ppt 提案 发布会 精彩发言 讲演' },
  { value: 'Briefcase', label: '步步高升公文包', category: 'study', theme: 'amber', component: Briefcase, keywords: '职场 升职 加薪 商业 商务 签约 事业里程碑' },
  { value: 'CheckCheck', label: '清单全部划勾', category: 'study', theme: 'emerald', component: CheckCheck, keywords: '全部完成 双勾 搞定 对钩 清空 今日事今日毕' },
  { value: 'FolderKanban', label: '项目大捷交付', category: 'study', theme: 'purple', component: FolderKanban, keywords: '项目交付 里程碑 任务集 协作 上线大捷 结项' },
  { value: 'ListTodo', label: '高效清单推进', category: 'study', theme: 'cyan', component: ListTodo, keywords: '待办 清单 todo 高效 今日行动 梳理 事项执行' },
  { value: 'Kanban', label: '敏捷冲刺看板', category: 'study', theme: 'cyan', component: Kanban, keywords: '敏捷 看板 流程 迭代 推进 任务流 状态追踪' },
  { value: 'TrendingUp', label: '业绩狂飙曲线上扬', category: 'study', theme: 'emerald', component: TrendingUp, keywords: '上涨 增长 进阶 提升 股票盈利 趋势大好 跃迁' },
  { value: 'BarChart3', label: '严密柱状复盘', category: 'study', theme: 'cyan', component: BarChart3, keywords: '柱状图 统计 报表 复盘 总结 效率分析 数据流' },
  { value: 'PieChart', label: '清晰全景饼图', category: 'study', theme: 'purple', component: PieChart, keywords: '饼图 占比 结构 财务规划 预算配比 资产布局' },
  { value: 'Languages', label: '掌握多国语言', category: 'study', theme: 'cyan', component: Languages, keywords: '语言 外语 翻译 英语 跨文化 对话 交流流利' },
  { value: 'Calculator', label: '理财精准精算', category: 'study', theme: 'emerald', component: Calculator, keywords: '计算器 财务 算账 核算 收益率 成本利润 精算' },
  { value: 'Binary', label: '底层二进制逻辑', category: 'study', theme: 'purple', component: Binary, keywords: '二进制 底层原理 逻辑 计算机 核心代码 本质' },
  { value: 'Workflow', label: '顺畅自动化流', category: 'study', theme: 'cyan', component: Workflow, keywords: '工作流 自动化 协同 流程串联 效率工具 管道' },
  { value: 'Network', label: '广阔行业人脉', category: 'study', theme: 'cyan', component: Network, keywords: '人脉 网络 社交 节点 联结 行业资源 协作网络' },
  { value: 'Milestone', label: '立下里程碑路碑', category: 'study', theme: 'amber', component: Milestone, keywords: '里程碑 阶段成功 标志 路碑 达成节点 纪念' },
  { value: 'Goal', label: '射门命中目标', category: 'study', theme: 'emerald', component: Goal, keywords: '进球 达标 命中 冲刺 任务终点 完成目标' },
  { value: 'Flame', label: '热血沸腾', category: 'study', theme: 'amber', component: Flame, keywords: '火焰 激情 燃烧 热血 冲劲 全力以赴' },
  { value: 'Telescope', label: '深空远眺天象', category: 'study', theme: 'purple', component: Telescope, keywords: '望远镜 天文 观星 远见 探索 宇宙 视野' },
  { value: 'Atom', label: '微观量子世界', category: 'study', theme: 'cyan', component: Atom, keywords: '原子 物理 科学 探索 严谨 微观 宇宙' },
  { value: 'Dna', label: '生命进化密码', category: 'study', theme: 'purple', component: Dna, keywords: '基因 dna 生命 进化 潜能 突破 健康密码' },
  { value: 'Puzzle', label: '拼齐最后拼图', category: 'study', theme: 'purple', component: Puzzle, keywords: '拼图 解谜 填补 完整 达成 智慧 探索' },
  { value: 'Feather', label: '轻柔羽毛笔触', category: 'study', theme: 'purple', component: Feather, keywords: '羽毛 笔 随笔 文艺 优雅 诗意 写作 灵感' },
  { value: 'Pen', label: '签字签约金笔', category: 'study', theme: 'amber', component: Pen, keywords: '钢笔 签字 笔 签约 约定 笔下生花 写作' },
  { value: 'PenLine', label: '落笔生花日记', category: 'study', theme: 'cyan', component: PenLine, keywords: '手账 日记 记录 随笔 涂鸦 写作 沉淀' },
  { value: 'FileSpreadsheet', label: '精密数据表格', category: 'study', theme: 'emerald', component: FileSpreadsheet, keywords: 'excel 表格 统计 报表 清晰 数据梳理' },
  { value: 'FileText', label: '万字长文初稿', category: 'study', theme: 'cyan', component: FileText, keywords: '文档 论文 报告 方案 文章 撰写 创作' },
  { value: 'Newspaper', label: '早间热点早报', category: 'study', theme: 'amber', component: Newspaper, keywords: '报纸 早报 资讯 动态 见识 见闻 晨读' },
  { value: 'Layers', label: '设计图层分层', category: 'study', theme: 'purple', component: Layers, keywords: '图层 层次 架构 逻辑清晰 步步为营 体系' },
  { value: 'Component', label: '模块化乐高件', category: 'study', theme: 'cyan', component: Component, keywords: '组件 模块 积木 组合 拆解 架构 复用' },
  { value: 'GitBranch', label: '开辟分支探索', category: 'study', theme: 'purple', component: GitBranch, keywords: '分支 git 版本 尝试 探索 新方案 并行' },
  { value: 'GitCommitHorizontal', label: '里程碑代码提交', category: 'study', theme: 'emerald', component: GitCommitHorizontal, keywords: 'commit 提交 记录 积累 足迹 踏实 前进' },
  { value: 'Figma', label: '大师UI原型图', category: 'study', theme: 'purple', component: Figma, keywords: 'figma 设计 原型 交互 视觉 灵感 美学 构想' },
  { value: 'FlaskConical', label: '灵感科学烧瓶', category: 'study', theme: 'purple', component: FlaskConical, keywords: '化学 实验 烧瓶 探索 发现 尝试 创造' },
  { value: 'FlaskRound', label: '神奇配方试管', category: 'study', theme: 'cyan', component: FlaskRound, keywords: '实验 调配 尝试 配方 研发 探索 创新' },
  { value: 'Tornado', label: '狂暴灵感风暴', category: 'study', theme: 'cyan', component: Tornado, keywords: '龙卷风 风暴 席卷 势不可挡 头脑风暴 气势' }
]

export const iconMap = Object.fromEntries(iconOptions.map((option) => [option.value, option.component]))
export const iconThemeMap = Object.fromEntries(iconOptions.map((option) => [option.value, option.theme]))

// Fallbacks for legacy Element Plus icon names
export const legacyMap = {
  Box: Package,
  Present: Gift,
  Goods: ShoppingBag,
  Handbag: ShoppingBag,
  Shop: ShoppingBag,
  Ticket: Ticket,
  Coin: Coins,
  Trophy: Trophy,
  Medal: Medal,
  Star: Star,
  MagicStick: Wand2,
  Goblet: Wine,
  Coffee: Coffee,
  Apple: Apple,
  Moon: Moon,
  SwitchButton: Zap,
  MilkTea: CupSoda,
  IceCream: IceCream2,
  Burger: Sandwich,
  Bowl: Utensils,
  Lollipop: Lollipop,
  Headset: Headphones,
  Film: Clapperboard,
  VideoPlay: Tv,
  Reading: BookOpen,
  Camera: Camera,
  Cellphone: Smartphone,
  Monitor: Monitor,
  Bicycle: Bike,
  Basketball: Dumbbell,
  Football: Dumbbell,
  Compass: Compass,
  Location: MapPin,
  Sunny: Sun,
  AlarmClock: AlarmClock,
  Discount: Tag,
  Key: Key,
  CollectionTag: Tag,
  Opportunity: Lightbulb,
  Lock: Key
}

export function getItemTheme(iconName) {
  return iconThemeMap[iconName] || 'cyan'
}

export function resolveShopIcon(icon) {
  return iconMap[icon] || legacyMap[icon] || Package
}
